version: '3'
services:
  app:
    build:
      context: .
    command: bash publish.sh
    volumes:
      - .:/usr/local/src/project
    env_file:
      - ./.env.npm
    stdin_open: true
    tty: true

